import pygame
import math
import random
import sys

pygame.init()

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Fun Race 3D - Curve Race")
clock = pygame.time.Clock()

# Colors
BLACK = (10, 10, 10)
WHITE = (235, 235, 235)
RED = (230, 45, 45)
BLUE = (55, 130, 255)
GREEN = (50, 210, 100)
YELLOW = (255, 220, 0)
CYAN = (50, 205, 255)
ORANGE = (255, 140, 30)
ROAD_COLOR = (68, 68, 68)
ROAD_EDGE_COLOR = (210, 210, 210)
GRASS_COLOR = (25, 80, 35)

# Race settings
PLAYER_SPEED = 210.0
AI_SPEED = 205.0
BACKWARD_SPEED = 145.0
ACCELERATION = 420.0
BRAKE = 600.0
MAX_REVERSE = 70.0

ROAD_WIDTH = 180
ROAD_HALF_WIDTH = ROAD_WIDTH // 2
START_POSITION = 0.0

# ----------------------------------------------------------------------
# ROAD
# The road is generated by rotating the travel direction through turns.
# This replaces the old square 90-degree road with smooth curved bends.
# ----------------------------------------------------------------------

road_points = []
road_distances = []
road_tangents = []
road_total_length = 0.0


def rotate_vector(x, y, angle_degrees):
    """Rotate a vector using a 2-D rotation matrix."""
    a = math.radians(angle_degrees)
    c = math.cos(a)
    s = math.sin(a)
    return x * c - y * s, x * s + y * c


def createRoad():
    global road_points, road_distances, road_tangents, road_total_length

    road_points = [(0.0, 350.0)]
    heading = 0.0  # 0 degrees = right
    x, y = road_points[0]

    # Each item is either ('straight', distance) or ('turn', angle, radius)
    commands = [
        ("straight", 650),
        ("turn", 90, 180),
        ("straight", 650),
        ("turn", -90, 180),
        ("straight", 800),
        ("turn", -90, 180),
        ("straight", 650),
        ("turn", 90, 180),
        ("straight", 850),
        ("turn", 90, 180),
        ("straight", 650),
        ("turn", -90, 180),
        ("straight", 800),
        ("turn", -90, 180),
        ("straight", 750),
    ]

    step = 10.0

    for command in commands:
        if command[0] == "straight":
            distance = command[1]
            count = max(1, int(distance / step))

            for _ in range(count):
                dx, dy = rotate_vector(step, 0, heading)
                x += dx
                y += dy
                road_points.append((x, y))

        else:
            _, turn_angle, radius = command

            # Arc length = radius * angle in radians.
            arc_length = radius * math.radians(abs(turn_angle))
            count = max(2, int(arc_length / step))
            angle_step = turn_angle / count

            # Start the circular arc from the current tangent.
            for _ in range(count):
                # Move along the tangent, then rotate the tangent.
                dx, dy = rotate_vector(step, 0, heading)
                x += dx
                y += dy
                road_points.append((x, y))
                heading += angle_step

    # Build cumulative distance and tangent data.
    road_distances = [0.0]
    road_tangents = []

    total = 0.0
    for i in range(len(road_points)):
        if i == 0:
            dx = road_points[1][0] - road_points[0][0]
            dy = road_points[1][1] - road_points[0][1]
        elif i == len(road_points) - 1:
            dx = road_points[-1][0] - road_points[-2][0]
            dy = road_points[-1][1] - road_points[-2][1]
        else:
            dx = road_points[i + 1][0] - road_points[i - 1][0]
            dy = road_points[i + 1][1] - road_points[i - 1][1]

        length = math.hypot(dx, dy)
        if length == 0:
            tangent = (1.0, 0.0)
        else:
            tangent = (dx / length, dy / length)

        road_tangents.append(tangent)

        if i > 0:
            segment_length = math.hypot(
                road_points[i][0] - road_points[i - 1][0],
                road_points[i][1] - road_points[i - 1][1]
            )
            total += segment_length
            road_distances.append(total)

    road_total_length = total


def getRoadPosition(position):
    position = max(0.0, min(position, road_total_length))

    # Binary search is unnecessary for this game size, but this loop is
    # simple and keeps the position logic easy to understand.
    for i in range(1, len(road_distances)):
        if position <= road_distances[i]:
            previous = road_distances[i - 1]
            segment_length = road_distances[i] - previous

            if segment_length == 0:
                ratio = 0.0
            else:
                ratio = (position - previous) / segment_length

            x1, y1 = road_points[i - 1]
            x2, y2 = road_points[i]

            x = x1 + (x2 - x1) * ratio
            y = y1 + (y2 - y1) * ratio
            tx, ty = road_tangents[i]

            return x, y, tx, ty

    x, y = road_points[-1]
    tx, ty = road_tangents[-1]
    return x, y, tx, ty


def getNormal(tx, ty):
    # Perpendicular vector to the road direction.
    return -ty, tx


def getWorldPosition(position, offset=0.0):
    x, y, tx, ty = getRoadPosition(position)
    nx, ny = getNormal(tx, ty)

    return x + nx * offset, y + ny * offset


# ----------------------------------------------------------------------
# CAMERA
# ----------------------------------------------------------------------

cameraX = 0.0
cameraY = 0.0


def worldToScreen(x, y):
    return int(x - cameraX), int(y - cameraY)


# ----------------------------------------------------------------------
# DRAW ROAD
# ----------------------------------------------------------------------

def drawRoad():
    screen.fill(GRASS_COLOR)

    # Draw only road pieces close to the player.
    visible_start = max(0.0, userPosition - 1100)
    visible_end = min(road_total_length, userPosition + 1500)

    start_index = 0
    while start_index < len(road_distances) - 1:
        if road_distances[start_index] >= visible_start:
            break
        start_index += 1

    end_index = start_index
    while end_index < len(road_distances) - 1 and road_distances[end_index] <= visible_end:
        end_index += 1

    for i in range(max(1, start_index), min(len(road_points), end_index + 1)):
        p1 = road_points[i - 1]
        p2 = road_points[i]

        tx, ty = road_tangents[i]
        nx, ny = getNormal(tx, ty)

        a = (p1[0] + nx * ROAD_HALF_WIDTH, p1[1] + ny * ROAD_HALF_WIDTH)
        b = (p2[0] + nx * ROAD_HALF_WIDTH, p2[1] + ny * ROAD_HALF_WIDTH)
        c = (p2[0] - nx * ROAD_HALF_WIDTH, p2[1] - ny * ROAD_HALF_WIDTH)
        d = (p1[0] - nx * ROAD_HALF_WIDTH, p1[1] - ny * ROAD_HALF_WIDTH)

        points = [
            worldToScreen(*a),
            worldToScreen(*b),
            worldToScreen(*c),
            worldToScreen(*d),
        ]

        pygame.draw.polygon(screen, ROAD_COLOR, points)

        # Road edges.
        pygame.draw.line(
            screen,
            ROAD_EDGE_COLOR,
            worldToScreen(*a),
            worldToScreen(*b),
            5,
        )
        pygame.draw.line(
            screen,
            ROAD_EDGE_COLOR,
            worldToScreen(*d),
            worldToScreen(*c),
            5,
        )

    drawCenterLine(visible_start, visible_end)


def drawCenterLine(start, end):
    # Dashed center line follows the curved road.
    dash_length = 35
    gap_length = 35
    position = start

    while position < end:
        dash_end = min(position + dash_length, end)
        points = []

        p = position
        while p <= dash_end:
            x, y = getWorldPosition(p)
            points.append(worldToScreen(x, y))
            p += 8

        if len(points) >= 2:
            pygame.draw.lines(screen, WHITE, False, points, 3)

        position += dash_length + gap_length


def drawRaceMarker(position, label, color):
    x, y, tx, ty = getRoadPosition(position)
    nx, ny = getNormal(tx, ty)

    # A line across the whole road.
    left = (x + nx * ROAD_HALF_WIDTH, y + ny * ROAD_HALF_WIDTH)
    right = (x - nx * ROAD_HALF_WIDTH, y - ny * ROAD_HALF_WIDTH)

    pygame.draw.line(
        screen,
        color,
        worldToScreen(*left),
        worldToScreen(*right),
        5,
    )

    sx, sy = worldToScreen(x, y)
    text = largeFont.render(label, True, color)
    shadow = largeFont.render(label, True, BLACK)

    rect = text.get_rect(center=(sx, sy - ROAD_HALF_WIDTH - 28))
    shadow_rect = shadow.get_rect(center=(sx + 2, sy - ROAD_HALF_WIDTH - 26))

    screen.blit(shadow, shadow_rect)
    screen.blit(text, rect)


# ----------------------------------------------------------------------
# OBSTACLES
# Obstacles move from one edge of the curved road to the other.
# There are no lanes; racers must manage their speed and timing.
# ----------------------------------------------------------------------

class Obstacle:
    def __init__(self, position, speed, start_side=1):
        self.position = position
        self.offset = -ROAD_HALF_WIDTH + 25 if start_side == 1 else ROAD_HALF_WIDTH - 25
        self.speed = speed
        self.direction = 1 if start_side == 1 else -1

    def update(self, dt):
        self.offset += self.speed * self.direction * dt

        limit = ROAD_HALF_WIDTH - 25

        if self.offset >= limit:
            self.offset = limit
            self.direction = -1
        elif self.offset <= -limit:
            self.offset = -limit
            self.direction = 1

    def world_position(self):
        return getWorldPosition(self.position, self.offset)


obstacles = []


def createObstacles():
    global obstacles

    obstacles = []
    positions = [
        650, 1250, 1900, 2550, 3200,
        3850, 4500, 5150, 5800, 6450
    ]

    for i, position in enumerate(positions):
        obstacles.append(
            Obstacle(
                position,
                55 + random.randint(0, 30),
                1 if i % 2 == 0 else -1,
            )
        )


def drawObstacle(obstacle):
    x, y = obstacle.world_position()
    sx, sy = worldToScreen(x, y)

    # Rotate the obstacle graphic so it follows the curved road direction.
    _, _, tx, ty = getRoadPosition(obstacle.position)
    angle = math.degrees(math.atan2(ty, tx))

    surface = pygame.Surface((72, 46), pygame.SRCALPHA)
    pygame.draw.rect(surface, BLACK, (0, 0, 72, 46), border_radius=8)
    pygame.draw.rect(surface, ORANGE, (5, 5, 62, 36), border_radius=5)
    pygame.draw.rect(surface, RED, (10, 10, 52, 26), border_radius=3)
    pygame.draw.line(surface, WHITE, (17, 23), (55, 23), 5)

    rotated = pygame.transform.rotate(surface, -angle)
    rect = rotated.get_rect(center=(sx, sy))
    screen.blit(rotated, rect)


def obstacleCollision(position, radius=30):
    player_x, player_y = getWorldPosition(position)

    for obstacle in obstacles:
        if abs(position - obstacle.position) > 60:
            continue

        obstacle_x, obstacle_y = obstacle.world_position()

        if math.hypot(player_x - obstacle_x, player_y - obstacle_y) < radius + 22:
            return True

    return False


# ----------------------------------------------------------------------
# RACERS
# ----------------------------------------------------------------------

class Racer:
    def __init__(self, name, color, is_player=False):
        self.name = name
        self.color = color
        self.is_player = is_player

        self.position = START_POSITION
        self.checkpoint = START_POSITION
        self.speed = 0.0

        self.finished = False
        self.finish_time = None
        self.collision_count = 0
        self.stun_timer = 0.0

    def reset(self):
        self.position = START_POSITION
        self.checkpoint = START_POSITION
        self.speed = 0.0
        self.finished = False
        self.finish_time = None
        self.collision_count = 0
        self.stun_timer = 0.0


racers = [
    Racer("YOU", RED, True),
    Racer("BLUE", BLUE),
    Racer("GREEN", GREEN),
]

userPosition = START_POSITION

raceTime = 0.0
raceStarted = False
winner = None


def updateCheckpoint(racer):
    # Checkpoints are time-saving restart points after a collision.
    distance = 900.0
    cp = int(racer.position // distance) * distance

    if cp > racer.checkpoint:
        racer.checkpoint = cp


def handleCollision(racer):
    if racer.finished:
        return

    if obstacleCollision(racer.position):
        racer.position = max(START_POSITION, racer.checkpoint - 15)
        racer.speed = 0.0
        racer.stun_timer = 0.65
        racer.collision_count += 1


def nearestObstacleAhead(position):
    nearest = None
    nearest_distance = float("inf")

    for obstacle in obstacles:
        distance = obstacle.position - position
        if 0 < distance < nearest_distance:
            nearest = obstacle
            nearest_distance = distance

    return nearest, nearest_distance


def updateAI(racer, dt):
    if racer.finished:
        return

    if racer.stun_timer > 0:
        racer.stun_timer -= dt
        return

    obstacle, distance = nearestObstacleAhead(racer.position)

    target_speed = AI_SPEED

    # AI has to time its movement around the moving obstacle.
    # It cannot change lanes. It slows down when an obstacle is too close.
    if obstacle is not None:
        relative_offset = abs(obstacle.offset)

        if distance < 115 and relative_offset < 55:
            target_speed = 45.0
        elif distance < 210 and relative_offset < 45:
            target_speed = 115.0
        elif distance < 320 and relative_offset < 35:
            target_speed = 165.0

    if racer.speed < target_speed:
        racer.speed = min(
            target_speed,
            racer.speed + ACCELERATION * dt
        )
    else:
        racer.speed = max(
            target_speed,
            racer.speed - BRAKE * dt
        )

    racer.position += racer.speed * dt
    racer.position = min(racer.position, finishPosition)

    updateCheckpoint(racer)
    handleCollision(racer)


# ----------------------------------------------------------------------
# FINISH / HUD
# ----------------------------------------------------------------------

font = pygame.font.Font(None, 27)
largeFont = pygame.font.Font(None, 40)
titleFont = pygame.font.Font(None, 50)

finishPosition = 0.0


def getRaceTime():
    return raceTime


def drawHUD():
    panel = pygame.Surface((SCREEN_WIDTH, 105), pygame.SRCALPHA)
    panel.fill((10, 10, 10, 225))
    screen.blit(panel, (0, 0))

    title = titleFont.render("CURVE RACE", True, WHITE)
    screen.blit(title, (25, 12))

    time_text = font.render(
        f"TIME: {raceTime:05.1f}s",
        True,
        YELLOW,
    )
    screen.blit(time_text, (270, 20))

    controls = font.render(
        "RIGHT: ACCELERATE    LEFT: BRAKE / REVERSE    ESC: QUIT",
        True,
        WHITE,
    )
    screen.blit(controls, (270, 52))

    # Live race positions.
    y = 88
    for racer in racers:
        progress = min(
            100,
            int((racer.position / finishPosition) * 100)
        )

        text = font.render(
            f"{racer.name}: {progress:3d}%   {racer.speed:3.0f}",
            True,
            racer.color,
        )
        screen.blit(text, (25 + racers.index(racer) * 205, y))


def drawFinishResults():
    if winner is None:
        return

    overlay = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
    overlay.fill((0, 0, 0, 150))
    screen.blit(overlay, (0, 0))

    title = titleFont.render(
        f"{winner.name} WINS!",
        True,
        winner.color,
    )
    title_rect = title.get_rect(
        center=(SCREEN_WIDTH // 2, 180)
    )
    screen.blit(title, title_rect)

    sorted_racers = sorted(
        racers,
        key=lambda r: r.finish_time if r.finish_time is not None else 999999
    )

    y = 250
    for index, racer in enumerate(sorted_racers, start=1):
        result = (
            f"{index}. {racer.name}   "
            f"{racer.finish_time:.2f}s   "
            f"Hits: {racer.collision_count}"
        )

        text = font.render(result, True, racer.color)
        rect = text.get_rect(
            center=(SCREEN_WIDTH // 2, y)
        )
        screen.blit(text, rect)
        y += 42

    restart = font.render(
        "Press R to race again    |    ESC to quit",
        True,
        WHITE,
    )
    rect = restart.get_rect(
        center=(SCREEN_WIDTH // 2, y + 25)
    )
    screen.blit(restart, rect)


def drawFrame():
    pygame.draw.rect(
        screen,
        WHITE,
        (4, 4, SCREEN_WIDTH - 8, SCREEN_HEIGHT - 8),
        4,
    )


# ----------------------------------------------------------------------
# MAIN GAME
# ----------------------------------------------------------------------

def resetRace():
    global raceTime, raceStarted, winner
    global cameraX, cameraY, userPosition

    for racer in racers:
        racer.reset()

    createObstacles()

    raceTime = 0.0
    raceStarted = False
    winner = None

    userPosition = START_POSITION

    start_x, start_y, _, _ = getRoadPosition(START_POSITION)

    cameraX = start_x - 250
    cameraY = start_y - 350


def main():
    global raceTime, raceStarted, winner
    global cameraX, cameraY, userPosition

    random.seed()

    createRoad()

    global finishPosition
    finishPosition = road_total_length - 80

    resetRace()

    running = True

    while running:
        dt = clock.tick(60) / 1000.0
        dt = min(dt, 0.05)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False

                if event.key == pygame.K_r and winner is not None:
                    resetRace()

        keys = pygame.key.get_pressed()

        if winner is None:
            if any(keys):
                # The race clock begins as soon as the player starts moving.
                if keys[pygame.K_RIGHT] or keys[pygame.K_LEFT]:
                    raceStarted = True

            if raceStarted:
                raceTime += dt

            player = racers[0]

            if player.stun_timer > 0:
                player.stun_timer -= dt
            else:
                if keys[pygame.K_RIGHT]:
                    player.speed = min(
                        PLAYER_SPEED,
                        player.speed + ACCELERATION * dt
                    )

                elif keys[pygame.K_LEFT]:
                    player.speed = max(
                        -MAX_REVERSE,
                        player.speed - BRAKE * dt
                    )

                else:
                    # Natural rolling slowdown.
                    if player.speed > 0:
                        player.speed = max(0, player.speed - 120 * dt)
                    elif player.speed < 0:
                        player.speed = min(0, player.speed + 120 * dt)

                player.position += player.speed * dt
                player.position = max(
                    START_POSITION,
                    min(player.position, finishPosition)
                )

                updateCheckpoint(player)
                handleCollision(player)

            userPosition = player.position

            updateAI(racers[1], dt)
            updateAI(racers[2], dt)

            # Every racer finishes on the same road; the first to reach
            # the finish line wins by having the shortest race time.
            for racer in racers:
                if not racer.finished and racer.position >= finishPosition:
                    racer.finished = True
                    racer.finish_time = raceTime

                    if winner is None:
                        winner = racer

            # Camera follows the player along the curved world.
            player_x, player_y = getWorldPosition(player.position)

            target_camera_x = player_x - 250
            target_camera_y = player_y - 350

            cameraX += (
                target_camera_x - cameraX
            ) * 7.0 * dt

            cameraY += (
                target_camera_y - cameraY
            ) * 7.0 * dt

        drawRoad()

        drawRaceMarker(
            START_POSITION,
            "START",
            GREEN,
        )

        drawRaceMarker(
            finishPosition,
            "FINISH",
            YELLOW,
        )

        for obstacle in obstacles:
            obstacle.update(dt if winner is None else 0)
            drawObstacle(obstacle)

        # Draw competitors and player directly on the center of the road.
        # There is no lane number and no A/D lane-switching logic.
        for racer in racers[1:]:
            x, y = getWorldPosition(racer.position)
            sx, sy = worldToScreen(x, y)

            pygame.draw.circle(screen, BLACK, (sx, sy), 15)
            pygame.draw.circle(screen, racer.color, (sx, sy), 10)
            pygame.draw.circle(screen, WHITE, (sx, sy), 10, 1)

        player = racers[0]
        x, y = getWorldPosition(player.position)
        sx, sy = worldToScreen(x, y)

        pygame.draw.circle(screen, BLACK, (sx, sy), 16)
        pygame.draw.circle(screen, player.color, (sx, sy), 11)
        pygame.draw.circle(screen, WHITE, (sx, sy), 11, 2)

        drawHUD()
        drawFinishResults()
        drawFrame()

        pygame.display.flip()

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
